# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_business_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='offers.Business'),
        ),
    ]
