# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0002_auto_20160106_0850'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0004_offer_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('apnsdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='push_notifications.APNSDevice')),
            ],
            options={
                'abstract': False,
            },
            bases=('push_notifications.apnsdevice',),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('range', models.PositiveIntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.Device')),
            ],
        ),
        migrations.CreateModel(
            name='UserDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='user_devices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.UserDevices'),
        ),
    ]
