# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 15:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_auto_20160304_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevices',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
