# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20160304_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='push_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
