# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_auto_20160304_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='range',
            field=models.PositiveIntegerField(default=3000),
        ),
    ]
